---
name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      command: # be careful when editing these, fusionauth-app expects certain commands
        type: choice
        options:
          - build # build only
          - publish # build & publish to nuget
          - release # build & release to svn
        default: build

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: /usr/bin/bash -l -e -o pipefail {0}
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          java-package: jre

      - name: install savant
        run: |
          curl -O https://repository.savantbuild.org/org/savantbuild/savant-core/2.0.0/savant-2.0.0.tar.gz
          tar xzvf savant-2.0.0.tar.gz
          savant-2.0.0/bin/sb --version
          SAVANT_PATH=$(realpath -s "./savant-2.0.0/bin")
          echo "${SAVANT_PATH}" >> $GITHUB_PATH
          mkdir -p ~/.savant/plugins
          cat << EOF > ~/.savant/plugins/org.savantbuild.plugin.java.properties
          21=${JAVA_HOME}
          EOF

      - name: compile
        run: sb compile

      ### Everything below this line will only run on a workflow_dispatch

      - name: nuget oidc login
        if: inputs.command == 'release' || inputs.command == 'publish'
        uses: NuGet/login@v1
        id: login
        with:
          user: fusionauth-platform

      - name: update savant properties file
        if: inputs.command == 'release' || inputs.command == 'publish'
        run: echo "nugetAPIKey=${{steps.login.outputs.NUGET_API_KEY}}" >> ~/.savant/config.properties

      - name: release to svn
        if: inputs.command == 'release'
        run: sb release

      - name: publish to nuget
        if: inputs.command == 'publish'
        run: sb publish
